chore: update package version

diff --git a/debian11-python-shadowsocksr/Dockerfile b/debian11-python-shadowsocksr/Dockerfile
--- a/debian11-python-shadowsocksr/Dockerfile
+++ b/debian11-python-shadowsocksr/Dockerfile
@@ -1,4 +1,4 @@
-FROM debian:bullseye-20241223-slim
+FROM debian:bullseye-20250113-slim
 LABEL authors="eric2369"
 
 RUN apt-get update \
@@ -11,7 +11,7 @@ USER shadowsocksr
 
 RUN git clone --branch manyuser "https://github.com/shadowsocksrr/shadowsocksr.git" /home/shadowsocksr/shadowsocksr
 
-RUN echo '#!/bin/bash' > /home/shadowsocksr/shadowsocksr/shadowsocks/start.sh \
+RUN echo '#!/bin/bash -euo pipefail' > /home/shadowsocksr/shadowsocksr/shadowsocks/start.sh \
     && echo 'cat << EOF > /home/shadowsocksr/shadowsocksr/shadowsocks/config.json' >> /home/shadowsocksr/shadowsocksr/shadowsocks/start.sh \
     && echo '{' >> /home/shadowsocksr/shadowsocksr/shadowsocks/start.sh \
     && echo '"server":"0.0.0.0",' >> /home/shadowsocksr/shadowsocksr/shadowsocks/start.sh \
diff --git a/debian12-codeserver/Dockerfile b/debian12-codeserver/Dockerfile
--- a/debian12-codeserver/Dockerfile
+++ b/debian12-codeserver/Dockerfile
@@ -1,4 +1,4 @@
-FROM debian:bookworm-20241223-slim
+FROM debian:bookworm-20250113-slim
 LABEL authors="eric2369"
 
 RUN apt-get update \
@@ -48,8 +48,7 @@ RUN curl "https://get.sdkman.io" --location --output - | bash
 
 RUN curl "https://sh.rustup.rs" --location --output - | bash -s -- -y --default-toolchain none
 
-RUN echo "#!/bin/sh" > /home/eric2369/start.sh \
-    && echo "set -eu" >> /home/eric2369/start.sh \
+RUN echo "#!/bin/bash -euo pipefail" > /home/eric2369/start.sh \
     && echo "exec /usr/bin/code-server --bind-addr 0.0.0.0:8080 --auth password --disable-telemetry --disable-update-check /home/eric2369/project" >> /home/eric2369/start.sh \
     && chmod +x /home/eric2369/start.sh
 
diff --git a/debian12-serverstatusrust-client/Dockerfile b/debian12-serverstatusrust-client/Dockerfile
--- a/debian12-serverstatusrust-client/Dockerfile
+++ b/debian12-serverstatusrust-client/Dockerfile
@@ -1,4 +1,4 @@
-FROM debian:bookworm-20241223-slim
+FROM debian:bookworm-20250113-slim
 LABEL authors="eric2369"
 
 RUN apt-get update \
@@ -27,7 +27,7 @@ RUN set -eux; \
     unzip /home/serverstatus/serverstatus.zip -d /home/serverstatus; \
     rm /home/serverstatus/serverstatus.zip
 
-RUN echo '#!/bin/bash' > /home/serverstatus/start.sh \
+RUN echo '#!/bin/bash -euo pipefail' > /home/serverstatus/start.sh \
     && echo 'exec /home/serverstatus/stat_client --addr "$ADDR" --user "$USER" --pass "$PASS" --interval "$INTERVAL"' >> /home/serverstatus/start.sh \
     && chmod +x /home/serverstatus/start.sh
 
diff --git a/debian12-serverstatusrust-server/Dockerfile b/debian12-serverstatusrust-server/Dockerfile
--- a/debian12-serverstatusrust-server/Dockerfile
+++ b/debian12-serverstatusrust-server/Dockerfile
@@ -1,4 +1,4 @@
-FROM debian:bookworm-20241223-slim
+FROM debian:bookworm-20250113-slim
 LABEL authors="eric2369"
 
 RUN apt-get update \
@@ -29,7 +29,7 @@ RUN set -eux; \
 
 RUN mkdir --parents /home/serverstatus/config \
     && mv /home/serverstatus/config.toml /home/serverstatus/config/config.toml \
-    && echo '#!/bin/bash' > /home/serverstatus/start.sh \
+    && echo '#!/bin/bash -euo pipefail' > /home/serverstatus/start.sh \
     && echo 'exec /home/serverstatus/stat_server -c /home/serverstatus/config/config.toml' >> /home/serverstatus/start.sh \
     && chmod +x /home/serverstatus/start.sh
 
