fix: correct shebang usage

diff --git a/debian11-python-shadowsocksr/Dockerfile b/debian11-python-shadowsocksr/Dockerfile
--- a/debian11-python-shadowsocksr/Dockerfile
+++ b/debian11-python-shadowsocksr/Dockerfile
@@ -11,7 +11,8 @@ USER shadowsocksr
 
 RUN git clone --branch manyuser "https://github.com/shadowsocksrr/shadowsocksr.git" /home/shadowsocksr/shadowsocksr
 
-RUN echo '#!/bin/bash -euo pipefail' > /home/shadowsocksr/shadowsocksr/shadowsocks/start.sh \
+RUN echo '#!/bin/bash' > /home/shadowsocksr/shadowsocksr/shadowsocks/start.sh \
+    && echo 'set -euo pipefail' >> /home/shadowsocksr/shadowsocksr/shadowsocks/start.sh \
     && echo 'cat << EOF > /home/shadowsocksr/shadowsocksr/shadowsocks/config.json' >> /home/shadowsocksr/shadowsocksr/shadowsocks/start.sh \
     && echo '{' >> /home/shadowsocksr/shadowsocksr/shadowsocks/start.sh \
     && echo '"server":"0.0.0.0",' >> /home/shadowsocksr/shadowsocksr/shadowsocks/start.sh \
diff --git a/debian12-codeserver/Dockerfile b/debian12-codeserver/Dockerfile
--- a/debian12-codeserver/Dockerfile
+++ b/debian12-codeserver/Dockerfile
@@ -48,7 +48,8 @@ RUN curl "https://get.sdkman.io" --location --output - | bash
 
 RUN curl "https://sh.rustup.rs" --location --output - | bash -s -- -y --default-toolchain none
 
-RUN echo "#!/bin/bash -euo pipefail" > /home/eric2369/start.sh \
+RUN echo "#!/bin/bash" > /home/eric2369/start.sh \
+    && echo "set -euo pipefail" >> /home/eric2369/start.sh \
     && echo "exec /usr/bin/code-server --bind-addr 0.0.0.0:8080 --auth password --disable-telemetry --disable-update-check /home/eric2369/project" >> /home/eric2369/start.sh \
     && chmod +x /home/eric2369/start.sh
 
